
megadepth:
    data_dir: "MegaDepth_undistort"
    data_processed_dir: "MegaDepth_undistort/data_processed_color/v2"
    data_file: "megadepth_2d3d_q500ov0.35-1covis3-10.npy"
    splits:
        train: ['0000'] #, '0001', '0002', '0003', '0004', '0005', '0007', '0012', '0013', '0015', '0016', '0017', '0020', '0021', '0023', '0024', '0025', '0026', '0027', '0033', '0036', '0039', '0041', '0042', '0043', '0044', '0047', '0048', '0049', '0056', '0058', '0060', '0062', '0063', '0067', '0071', '0076', '0083', '0087', '0094', '0095', '0098', '0099', '0100', '0102', '0103', '0104', '0105', '0107', '0122', '0130', '0143', '0147', '0168', '0175', '0176', '0178', '0183', '0186', '0189', '0197', '0200', '0204', '0212', '0217', '0235', '0257', '0258', '0269', '0271', '0277', '0285', '0303', '0307', '0331', '0341', '0366', '0377', '0380', '0387', '0389', '0402', '0430', '0478', '0482', '0505', '0559', '0733', '0768', '0860', '1001', '1017', '1589', '3346', '4541', '5015', '5016', '5017', '5018']
        val: ['0019'] #, '0022', '0046', '0050', '0078', '0086', '0101', '0115', '0117', '0160', '0162', '0185', '0286', '0406', '0493', '5014']
        test: ['0034', '0037', '0061', '0064', '0065', '0070', '0090', '0121', '0129', '0137', '0141', '0149', '0151', '0156', '0177', '0181', '0190', '0205', '0209', '0214', '0223', '0224', '0231', '0237', '0238', '0240', '0243', '0252', '0265', '0275', '0281', '0290', '0294', '0299', '0306', '0312', '0323', '0326', '0327', '0335', '0348', '0360', '0394', '0407', '0411', '0412', '0443', '0446', '0455', '0472', '0474', '0476', '0496']

# 7Scenes Official Splitted Version 
default_7scenes_v2: &default_7scenes_v2
    data_dir: "7scenes"
    data_file: "7scenes_2d3d.npy"
    splits:
        test: ['chess', 'fire', 'heads', 'office', 'pumpkin', 'redkitchen', 'stairs']
        chess: ['chess']
        fire: ['fire']
        heads: ['heads']
        office: ['office']
        pumpkin: ['pumpkin']
        redkitchen: ['redkitchen']
        stairs: ['stairs']

7scenes_sift_v2:
    <<: *default_7scenes_v2
    data_processed_dir: "7scenes/data_processed_v2/densevlad-top10-sift"
        
7scenes_superpoint_v2:
    <<: *default_7scenes_v2
    data_processed_dir: "7scenes/data_processed_v2/densevlad-top10-superpoint"
    
    
# Cambridge Official Splitted Version     
cambridge:
    data_dir: "cambridge"
    data_processed_dir: "cambridge/data_processed/query-netvlad10"
    data_file: "cambridge_2d3d.npy"
    splits:
        all: ["StMarysChurch"]
        # , "OldHospital", "ShopFacade", "StMarysChurch"]
        kings: ["KingsCollege"]
        old: ["OldHospital"]
        shop: ["ShopFacade"]
        stmarys: ["StMarysChurch"]

cambridge_sift:
    data_dir: "cambridge"
    data_processed_dir: "cambridge/data_processed/query-netvlad10-sift"
    data_file: "cambridge_2d3d.npy"
    splits:
        test: ["KingsCollege", "OldHospital", "ShopFacade", "StMarysChurch"]
        kings: ["KingsCollege"]
        old: ["OldHospital"]
        shop: ["ShopFacade"]
        stmarys: ["StMarysChurch"]

